version: '3.8'

services:
  app:
    container_name: nextjs-app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/mydb?schema=public
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
